### ISSUE TITLE
Fehlermeldung bei grossen Kartenausschnitten

### ISSUE THREAD

**Issue by chatelao** [hholzgra/ocitysmap#38]
```
Traceback (most recent call last):
  File "/home/maposmatic/maposmatic/scripts/render.py", line 508, in run
    output_count = renderer.render(config, self.job.layout,
  File "/home/maposmatic/ocitysmap/ocitysmap/__init__.py", line 586, in render
    self._render_one(config, tmpdir, renderer_cls,
  File "/home/maposmatic/ocitysmap/ocitysmap/__init__.py", line 698, in _render_one
    surface.finish()
ocitysmap.cairo.MemoryError: out of memory
```

https://maposmatic.osm-baustelle.de/results//2022/03/16/210149_2022-03-16_12-06_ukraine-errors.txt

**Comment by hholzgra** [comment]
The MapOSMatic web frontend now has a more clear error message:

![Screenshot_2023-03-23_22-46-31](https://user-images.githubusercontent.com/451772/227371827-c9d97ee1-2e03-447b-821e-f850f387c46d.png)

For command line users the backtrace output should be clear enough.

For the out-of-memory errors on rather small map areas see #66 now
